monolog:
    handlers:
        normal_log:
            type: rotating_file
            # log to var/log/(environment).log
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: debug
            max_files: 30
        error_log:
            type: rotating_file
            # log to var/log/(environment)_error.log
            path: "%kernel.logs_dir%/%kernel.environment%_error.log"
            # log error messages
            level: error
            max_files: 30
