index:
    path: /
    defaults: { _controller: 'App\Controller\ListFinesController::index' }

payment_handler:
    path: /pay
    controller: App\Controller\PayController::index

history:
    path: /history
    controller: App\Controller\HistoryController::index
