# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: UAL Payments Documentation
subtitle: Documentation for University of Arizona Payments application

# Insert your disqus shortname
#disqus:
#    shortname:
